default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: searchaddressapi_development

test:
  <<: *default
  database: searchaddressapi_test

production:
  <<: *default
  database: searchaddress_production
  username: searchaddress
  password: <%= ENV['SEARCHADDRESSAPI_DATABASE_PASSWORD'] %>
